# Generated by Django 2.2.7 on 2020-02-21 20:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Build')),
                ('video', models.URLField(max_length=254, verbose_name='Video Clase')),
                ('match', models.CharField(choices=[('TvT', 'Terran vs Terran'), ('TvZ', 'Terran vs Zerg'), ('TvP', 'Terran vs Protoss'), ('PvP', 'Protoss vs Protoss'), ('PvT', 'Protoss vs Terran'), ('PvZ', 'Protoss vs Zerg'), ('ZvZ', 'Zerg vs Zerg'), ('ZvT', 'Zerg vs Terran'), ('ZvP', 'Zerg vs Protoss')], default='TvT', max_length=3)),
                ('build_order', ckeditor.fields.RichTextField()),
                ('liga_main', models.CharField(choices=[('Br', 'Bronce'), ('Pl', 'Plata'), ('Or', 'Oro'), ('Pt', 'Platino'), ('Dm', 'Diamante'), ('Ms', 'Master'), ('GM', 'GrandMaster')], default='Br', max_length=2)),
                ('liga_oponente', models.CharField(choices=[('Br', 'Bronce'), ('Pl', 'Plata'), ('Or', 'Oro'), ('Pt', 'Platino'), ('Dm', 'Diamante'), ('Ms', 'Master'), ('GM', 'GrandMaster')], default='Br', max_length=2)),
                ('observaciones', ckeditor.fields.RichTextField()),
                ('tut_from', models.CharField(max_length=50, verbose_name='De')),
                ('replay', models.URLField(max_length=254, verbose_name='Replay')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('O', 'Obsoleto')], default='Br', max_length=2)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
        ),
    ]
