# Generated by Django 2.2.7 on 2020-02-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('O', 'Obsoleto')], default='A', max_length=1),
        ),
    ]
