# Generated by Django 2.2.7 on 2020-02-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startab', '0002_auto_20200221_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='slug',
            field=models.CharField(default='entrada_sdfs', max_length=100, verbose_name='Slug'),
        ),
    ]
